name: Beagle Automated Tests

on: workflow_dispatch

jobs:
    run-automated-tests:
        name: Run automated tests
        runs-on: macos-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Cache fastlane dependences
                uses: actions/cache@v2
                env:
                    fastlane-cache-key: fastlane-cache-tests
                    fastlane-path: ~/.gem
                with:
                    path: ${{ env.fastlane-path }}
                    key: ${{ runner.os }}-build-${{ env.fastlane-cache-key }}-${{ hashFiles('Gemfile.lock') }}
            -   name: Install Fastlane
                run: bundle install

            -   name: Cache gradle dependences
                uses: actions/cache@v2
                env:
                    gradle-cache-key: gradle-cache-tests
                    gradle-path: ~/.gradle
                with:
                    path: ${{ env.gradle-path }}
                    key: ${{ runner.os }}-build-${{ env.gradle-cache-key }}-${{ hashFiles('buildSrc/**') }}
            -   name: Deploy backend
                run: bash fastlane/automatedTests/deploy_tests_backend.sh

            -   name: Test Android
                run: bash fastlane/automatedTests/run_android_automation.sh
                env:
                    ANDROID_SDK_ROOT: /Users/runner/Library/Android/sdk

            -   name: Test iOS
                run: bundle exec fastlane automated_tests run_ios_automation

            -   name: Cleanup
                run: bundle exec fastlane automated_tests cleanup