name: Beagle Automated Tests

on: workflow_dispatch

jobs:
    run-automated-tests:
        name: Run automated tests
        runs-on: macos-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Cache fastlane dependences
                uses: actions/cache@v2
                env:
                    fastlane-cache-key: fastlane-cache-test
                    fastlane-path: ~/.gem
                with:
                    path: ${{ env.fastlane-path }}
                    key: ${{ runner.os }}-build-${{ env.fastlane-cache-key }}-${{ hashFiles('Gemfile.lock') }}
            -   name: Install Fastlane
                run: bundle config set path '~/.gem' && bundle install

            -   name: Cache backend gradle dependencies
                uses: actions/cache@v2
                env:
                    gradle-cache-key: gradle-cache-tests
                    gradle-path: ~/.gradle
                with:
                    path: ${{ env.gradle-path }}
                    key: ${{ runner.os }}-build-${{ env.gradle-cache-key }}-${{ hashFiles('buildSrc/backend/**') }}
            -   name: Start backend in background
                run: bash fastlane/automatedTests/start_test_backend.sh backend

            -   name: Cleanup
                run: bundle exec fastlane automated_tests cleanup