name: Beagle Automated Tests

on: push

jobs:
    run-automated-tests:
        name: Run automated tests
        runs-on: macos-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Cache fastlane dependences
                uses: actions/cache@v2
                env:
                    fastlane-cache-key: fastlane-cache
                    fastlane-path: ~/.gem
                with:
                    path: ${{ env.fastlane-path }}
                    key: ${{ runner.os }}-build-${{ env.fastlane-cache-key }}-${{ hashFiles('Gemfile.lock') }}
            -   name: Install Fastlane
                run: bundle install

            -   name: Deploy backend
                run: bundle exec fastlane automated_tests deploy_tests_backend

            -   name: Cleanup
                run: bundle exec fastlane automated_tests cleanup