name: Beagle Release

on:
    push:
        tags:
            - '*'
jobs:
    run-automated-tests:
        name: Run automated tests
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2.1.0
              with:
                  fetch-depth: '0'
                  ref: 'master'
            - name: Install Fastlane
              run: bundle install
            - name: Deploy backend
              env:
                TODO: ${{ secrets.TODO }}
              run: bundle exec fastlane deploy_tests_backend
            - name: Run iOS automated tests
              env:
                TODO: ${{ secrets.TODO }}
              run: bundle exec fastlane run_ios_automation
            - name: Run android automated tests
              env:
                TODO: ${{ secrets.TODO }}
              run: bundle exec fastlane run_android_automation
            - name: Deploy React website
              env:
                TODO: ${{ secrets.TODO }}
              run: bundle exec fastlane deploy_react_website
            - name: Run react automated tests
              env:
                TODO: ${{ secrets.TODO }}
              run: bundle exec fastlane run_react_automation
            - name: Deploy Angular website
              env:
                TODO: ${{ secrets.TODO }}
              run: bundle exec fastlane deploy_angular_website
            - name: Run react automated tests
              env:
                TODO: ${{ secrets.TODO }}
              run: bundle exec fastlane run_angular_automation
        
