name: Publish Beagle test backend

on: push

jobs:
    publish:
        name: Publish test backend to GitHub packages
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Cache fastlane dependencies
                uses: actions/cache@v2
                env:
                    fastlane-cache-key: fastlane-cache-test
                    fastlane-path: ~/.gem
                with:
                    path: ${{ env.fastlane-path }}
                    key: ${{ runner.os }}-build-${{ env.fastlane-cache-key }}-${{ hashFiles('Gemfile.lock') }}
            -   name: Install Fastlane
                run: bundle config set path '~/.gem' && bundle install

            -   name: Cache gradle backend dependencies
                uses: actions/cache@v2
                env:
                    gradle-cache-key: gradle-cache-tests
                    gradle-path: ~/.gradle
                with:
                    path: ${{ env.gradle-path }}
                    key: ${{ runner.os }}-build-${{ env.gradle-cache-key }}-${{ hashFiles('buildSrc/**') }}
            -   name: Create backend image and publish it
                run: bundle exec fastlane automated_tests publish_backend
                env:
                    user: ${{ github.actor }}
                    token: ${{ secrets.GITHUB_TOKEN }}
                    repository: ${{ github.repository }}
                    registry: docker.pkg.github.com
                    image: automated-test-backend
                    sha: ${{ github.sha }}
